[package]
name = "rust_ray_tracing"
version = "0.1.1"
authors = ["colton"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"
rand = "0.8.5"
